export const FETCH_USER = 'FETCH_USER';
export const FETCH_CARDS = 'FETCH_CARDS';
export const SHOW_ALERT = 'SHOW_ALERT';
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const ADD_BLACKLIST_COUNTRIES = 'ADD_BLACKLIST_COUNTRIES';
